import { Serie } from "./serie.js";
export const series = [
    new Serie("Breaking Bad", "AMC", 5, "Set and filmed in Albuquerque, New Mexico, the series tells the story of Walter White, a struggling and depressed high school chemistry teacher who is diagnosed with lung cancer.", "https://www.imdb.com/title/tt0903747/?ref_=nv_sr_srsg_3_tt_8_nm_0_in_0_q_break", "https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_.jpg"),
    new Serie("Orange Is the New Black", "Netflix", 6, "The series begins revolving around Piper Chapman, a woman in her thirties living in New York City who is sentenced to 15 months in Litchfield Penitentiary.", "https://www.imdb.com/title/tt2372162/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_orange", "https://akns-images.eonline.com/eol_images/Entire_Site/201869/rs_634x939-180709061638-634-oitnb-s6.ch.070918.jpg?fit=around%7C634:939&output-quality=90&crop=634:939;center,top"),
    new Serie("Game of Thrones", "HBO", 7, "American fantasy drama.", "https://www.imdb.com/title/tt0944947/?ref_=nv_sr_srsg_0_tt_8_nm_0_in_0_q_game", "https://m.media-amazon.com/images/M/MV5BOGY3NTg1ODMtOGIzZS00YWFiLTgzYzktNzBiYWZkYjcwNGRhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    new Serie("The Big Bang Theory", "CBS", 12, "Leonard and Sheldon are brilliant physicists.", "https://www.imdb.com/title/tt0898266/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_the%2520big", "https://m.media-amazon.com/images/M/MV5BZjgzY2QyNzItNDhhYi00ZWIwLWFjN2UtZDJkN2MxYWNjMmJjXkEyXkFqcGc@._V1_.jpg"),
    new Serie("Sherlock", "BBC", 4, "Sherlock depicts consulting detective Sherlock Holmes.", "https://www.imdb.com/title/tt1475582/?ref_=nv_sr_srsg_0_tt_7_nm_1_in_0_q_sherl", "https://m.media-amazon.com/images/M/MV5BNTQzNGZjNDEtOTMwYi00MzFjLWE2ZTYtYzYxYzMwMjZkZDc5XkEyXkFqcGc@._V1_.jpg"),
    new Serie("A Very English Scandal", "BBC", 2, "A Very English Scandal is a fact-based three-part British television comedy-drama miniseries.", "https://www.imdb.com/title/tt6938856/", "https://m.media-amazon.com/images/M/MV5BNTQ5NDI0MTQ0MV5BMl5BanBnXkFtZTgwNDEzNTc1NTM@._V1_.jpg"),
    new Serie("The Crown", "Netflix", 4, "The Crown is a historical drama streaming television series about the reign of Queen Elizabeth II.", "https://www.imdb.com/title/tt4786824/", "https://m.media-amazon.com/images/M/MV5BODcyODZlZDMtZGE0Ni00NjBhLWJlYTAtZDdlNWY3MzkwMGVhXkEyXkFqcGc@._V1_.jpg"),
    new Serie("The Mandalorian", "Disney+", 2, "The Mandalorian is an American space Western television series created by Jon Favreau.", "https://www.imdb.com/title/tt8111088/", "https://m.media-amazon.com/images/M/MV5BNjgxZGM0OWUtZGY1MS00MWRmLTk2N2ItYjQyZTI1OThlZDliXkEyXkFqcGc@._V1_.jpg"),
    new Serie("The Witcher", "Netflix", 2, "The Witcher is a Polish-American fantasy drama series produced by Lauren Schmidt Hissrich.", "https://www.imdb.com/title/tt5180504/", "https://m.media-amazon.com/images/M/MV5BMTQ5MDU5MTktMDZkMy00NDU1LWIxM2UtODg5OGFiNmRhNDBjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"),
    new Serie("The Sopranos", "HBO", 6, "The Sopranos is an American crime drama television series created by David Chase.", "https://www.imdb.com/title/tt0141842/", "https://m.media-amazon.com/images/M/MV5BMjRmMTNiMTQtMDg1ZS00MGM1LWE1MGUtYjEzMGFjNWUzOWRkXkEyXkFqcGc@._V1_.jpg")
];
